"""empty message

Revision ID: 09edbff1e262
Revises: 1fb931fe6a13
Create Date: 2024-02-18 22:13:08.117171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09edbff1e262'
down_revision = '1fb931fe6a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('baseHp', sa.Integer(), nullable=False),
    sa.Column('baseAttack', sa.Integer(), nullable=False),
    sa.Column('baseDefense', sa.Integer(), nullable=False),
    sa.Column('spriteImage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon')
    # ### end Alembic commands ###
